// Register
export const REGISTERED_FAIL = 'REGISTERED_FAIL';

// Login
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAIL = 'LOG_IN_FAIL';
export const LOG_OUT = 'LOG_OUT';

// Form
export const SET_FIELD_DATA = 'SET_FIELD_VALUE';
export const CLEAR_FORM = 'CLEAR_FORM';
export const INIT_FIELD = 'INIT_FIELD';
export const SET_FIELD_VALUE = 'SET_FIELD_VALUE';
export const SET_FIELD_ERRORS = 'SET_FIELD_ERRORS';
export const SET_FIELD_FOCUS = 'SET_FIELD_FOCUS';

// News
export const CREATE_NEW_FAIL = 'CREATE_NEW_FAIL';
export const CREATE_NEW_SUCCESS = 'CREATE_NEW_SUCCESS';
export const DELETE_NEW_FAIL = 'DELETE_NEW_FAIL';
export const DELETE_NEW_SUCCESS = 'DELETE_NEW_SUCCESS';
export const EDIT_NEW_FAIL = 'EDIT_NEW_FAIL';
export const EDIT_NEW_SUCCESS = 'EDIT_NEW_SUCCESS';
export const GET_NEW_FAIL = 'GET_NEW_FAIL';
export const GET_NEW_SUCCESS = 'GET_NEW_SUCCESS';
export const GET_NEWS_FAIL = 'GET_NEWS_FAIL';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';

// Subjects
export const GET_SUBJECTS_FAIL = 'GET_SUBJECTS_FAIL';
export const GET_SUBJECTS_SUCCESS = 'GET_SUBJECTS_SUCCESS';
export const GET_SUBJECT_FAIL = 'GET_SUBJECT_FAIL';
export const GET_SUBJECT_SUCCESS = 'GET_SUBJECT_SUCCESS';
export const CREATE_SUBJECT_SUCCESS = 'CREATE_SUBJECT_SUCCESS';
export const CREATE_SUBJECT_FAIL = 'CREATE_SUBJECT_FAIL';
export const SAVE_SUBJECT_SUCCESS = 'SAVE_SUBJECT_SUCCESS';
export const SAVE_SUBJECT_FAIL = 'SAVE_SUBJECT_FAIL';
export const EDIT_SUBJECT_SUCCESS = 'EDIT_SUBJECT_SUCCESS';
export const EDIT_SUBJECT_FAIL = 'EDIT_SUBJECT_FAIL';
export const DELETE_SUBJECT_SUCCESS = 'DELETE_SUBJECT_SUCCESS';
export const DELETE_SUBJECT_FAIL = 'DELETE_SUBJECT_FAIL';
export const SUBJECT_SUBSCRIBE_SUCCESS = 'SUBJECT_SUBSCRIBE_SUCCESS';
export const SUBJECT_SUBSCRIBE_FAIL = 'SUBJECT_SUBSCRIBE_FAIL';

// Updates
export const GET_UPDATES_SUCCESS = 'GET_UPDATES_SUCCESS'
export const GET_UPDATES_FAIL = 'GET_UPDATES_FAIL'
export const GET_UPDATES_COUNT_SUCCESS = 'GET_UPDATES_COUNT_SUCCESS'
export const GET_UPDATES_COUNT_FAIL = 'GET_UPDATES_COUNT_FAIL'

// Specialities
export const GET_SPECIALITIES_SUCCESS = 'GET_SPECIALITIES_SUCCESS';
export const GET_SPECIALITIES_FAIL = 'GET_SPECIALITIES_FAIL';
export const GET_SPECIALITY_SUCCESS = 'GET_SPECIALITY_SUCCESS';
export const GET_SPECIALITY_FAIL = 'GET_SPECIALITY_FAIL';
export const CREATE_SPECIALITY_SUCCESS = 'CREATE_SPECIALITY_SUCCESS';
export const CREATE_SPECIALITY_FAIL = 'CREATE_SPECIALITY_FAIL';
export const EDIT_SPECIALITY_SUCCESS = 'EDIT_SPECIALITY_SUCCESS';
export const EDIT_SPECIALITY_FAIL = 'EDIT_SPECIALITY_FAIL';
export const DELETE_SPECIALITY_SUCCESS = 'DELETE_SPECIALITY_SUCCESS';
export const DELETE_SPECIALITY_FAIL = 'DELETE_SPECIALITY_FAIL';

// Students
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_FAIL = 'GET_STUDENTS_FAIL';
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS';
export const GET_STUDENT_FAIL = 'GET_STUDENT_FAIL';
export const SAVE_STUDENT_SUCCESS = 'SAVE_STUDENT_SUCCESS';
export const SAVE_STUDENT_FAIL = 'SAVE_STUDENT_FAIL';
export const EDIT_STUDENT_SUCCESS = 'EDIT_STUDENT_SUCCESS';
export const EDIT_STUDENT_FAIL = 'EDIT_STUDENT_FAIL';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAIL = 'DELETE_STUDENT_FAIL';

// Teachers
export const GET_TEACHERS_SUCCESS = 'GET_TEACHERS_SUCCESS';
export const GET_TEACHERS_FAIL = 'GET_TEACHERS_FAIL';
export const GET_TEACHER_SUCCESS = 'GET_TEACHER_SUCCESS';
export const GET_TEACHER_FAIL = 'GET_TEACHER_FAIL';
export const SAVE_TEACHER_SUCCESS = 'SAVE_TEACHER_SUCCESS';
export const SAVE_TEACHER_FAIL = 'SAVE_TEACHER_FAIL';
export const EDIT_TEACHER_SUCCESS = 'EDIT_TEACHER_SUCCESS';
export const EDIT_TEACHER_FAIL = 'EDIT_TEACHER_FAIL';
export const DELETE_TEACHER_SUCCESS = 'DELETE_TEACHER_SUCCESS';
export const DELETE_TEACHER_FAIL = 'DELETE_TEACHER_FAIL';
export const SEND_TEACHER_INVITATION_SUCCESS = 'SEND_TEACHER_INVITATION_SUCCESS';
export const SEND_TEACHER_INVITATION_FAIL = 'SEND_TEACHER_INVITATION_FAIL';

// USERS

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

// EVENTS
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAIL = 'GET_EVENTS_FAIL';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT_FAIL = 'GET_EVENT_FAIL';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAIL = 'CREATE_EVENT_FAIL';
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS';
export const EDIT_EVENT_FAIL = 'EDIT_EVENT_FAIL';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAIL = 'DELETE_EVENT_FAIL';

// Exams
export const GET_EXAMS_SUCCESS = 'GET_EXAMS_SUCCESS';
export const GET_EXAMS_FAIL = 'GET_EXAMS_FAIL';
export const GET_EXAM_SUCCESS = 'GET_EXAM_SUCCESS';
export const GET_EXAM_FAIL = 'GET_EXAM_FAIL';
export const CREATE_EXAM_SUCCESS = 'CREATE_EXAM_SUCCESS';
export const CREATE_EXAM_FAIL = 'CREATE_EXAM_FAIL';
export const EDIT_EXAM_SUCCESS = 'EDIT_EXAM_SUCCESS';
export const EDIT_EXAM_FAIL = 'EDIT_EXAM_FAIL';
export const DELETE_EXAM_SUCCESS = 'DELETE_EXAM_SUCCESS';
export const DELETE_EXAM_FAIL = 'DELETE_EXAM_FAIL';

// IMAGES
export const CREATE_IMAGE_FAIL = 'CREATE_IMAGE_FAIL';
export const CREATE_IMAGE_SUCCESS = 'CREATE_IMAGE_SUCCESS';
export const DELETE_IMAGE_FAIL = 'DELETE_IMAGE_FAIL';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const EDIT_IMAGE_FAIL = 'EDIT_IMAGE_FAIL';
export const EDIT_IMAGE_SUCCESS = 'EDIT_IMAGE_SUCCESS';
export const GET_IMAGE_FAIL = 'GET_IMAGE_FAIL';
export const GET_IMAGE_SUCCESS = 'GET_IMAGE_SUCCESS';
export const GET_IMAGES_FAIL = 'GET_IMAGES_FAIL';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';